import crypto from "crypto";
import fs from "fs";
import path from "path";

import { loadLocalConfig } from "./config.js";

/**
 * Content revision tracking for development.
 *
 * Content is read from disk at request time and never imported, so a bundler
 * has no idea those files exist: editing an MDX file produces no module change,
 * the dev server has nothing to push, and the page the author is looking at goes
 * stale until they reload by hand.
 *
 * Writing the content's revision into a real module that the site imports gives
 * the graph an actual change, which the dev server turns into an update. That
 * makes live preview work under any bundler — Turbopack, Webpack or Vite — with
 * no bundler-specific plugin.
 */

/** Default location of the generated module, relative to the project root. */
export const DEFAULT_CONTENT_REVISION_FILE = ".leadcms/content-revision.js";

/**
 * Fingerprint of every file under `contentDir`: path, size and mtime.
 *
 * Size is included alongside mtime because mtime granularity is one second on
 * some filesystems, which would otherwise hide a rewrite made within the same
 * second.
 */
export function computeContentRevision(contentDir?: string): string {
  const root = path.resolve(contentDir ?? loadLocalConfig().contentDir);
  const hash = crypto.createHash("sha1");

  const walk = (dir: string): void => {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of [...entries].sort((a, b) => a.name.localeCompare(b.name))) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
        continue;
      }
      try {
        const { size, mtimeMs } = fs.statSync(full);
        hash.update(`${full}:${size}:${mtimeMs}`);
      } catch {
        // The file vanished mid-walk (a pull replacing content, say); the next
        // revision will account for it.
      }
    }
  };

  walk(root);
  return hash.digest("hex").slice(0, 12);
}

/**
 * Write the revision module. Returns true when the file's contents changed,
 * so callers can avoid touching it — and triggering a rebuild — needlessly.
 */
export function writeContentRevision(revision: string, revisionFile?: string): boolean {
  const target = path.resolve(revisionFile ?? DEFAULT_CONTENT_REVISION_FILE);
  const contents =
    "// Generated by @leadcms/sdk — do not edit.\n" +
    "// Changes whenever the content directory changes, which is what lets the\n" +
    "// dev server push content edits to the open page. Unused at runtime.\n" +
    `export const CONTENT_REVISION = ${JSON.stringify(revision)};\n`;

  let existing: string | null = null;
  try {
    existing = fs.readFileSync(target, "utf-8");
  } catch {
    existing = null;
  }
  if (existing === contents) return false;

  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents);
  return true;
}

/**
 * Create the revision module if it is absent.
 *
 * Production builds import it like any other module but never need it to
 * change, so this is what a `prebuild` step should call. Safe to run on a
 * checkout where the file is gitignored.
 */
export function ensureContentRevisionFile(revisionFile?: string): void {
  const target = path.resolve(revisionFile ?? DEFAULT_CONTENT_REVISION_FILE);
  if (fs.existsSync(target)) return;
  writeContentRevision("build", target);
}

export interface WatchContentRevisionOptions {
  contentDir?: string;
  revisionFile?: string;
  /** Coalesce bursts of filesystem events, in milliseconds. */
  debounceMs?: number;
  onChange?: (revision: string) => void;
  onError?: (error: Error) => void;
}

/**
 * Watch the content directory and keep the revision module in step.
 *
 * @returns a function that stops watching.
 */
export function watchContentRevision(options: WatchContentRevisionOptions = {}): () => void {
  const contentDir = path.resolve(options.contentDir ?? loadLocalConfig().contentDir);
  const revisionFile = path.resolve(options.revisionFile ?? DEFAULT_CONTENT_REVISION_FILE);
  const debounceMs = options.debounceMs ?? 150;

  let revision = computeContentRevision(contentDir);
  writeContentRevision(revision, revisionFile);

  let timer: NodeJS.Timeout | null = null;
  const onFsEvent = (): void => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      const next = computeContentRevision(contentDir);
      if (next === revision) return;
      revision = next;
      writeContentRevision(revision, revisionFile);
      options.onChange?.(revision);
    }, debounceMs);
  };

  let watcher: fs.FSWatcher | null = null;
  let poll: NodeJS.Timeout | null = null;

  try {
    watcher = fs.watch(contentDir, { recursive: true }, onFsEvent);
  } catch (error) {
    // Recursive watching is unsupported on some platforms; fall back to polling
    // so live preview still works, just a little less promptly.
    options.onError?.(error as Error);
    poll = setInterval(onFsEvent, 1000);
  }

  return () => {
    if (timer) clearTimeout(timer);
    if (poll) clearInterval(poll);
    watcher?.close();
  };
}
