#!/usr/bin/env node
/**
 * Interactive LeadCMS initialization script
 * Guides users through setting up their LeadCMS configuration
 */

import readline from 'readline';
import fs from 'fs';
import path from 'path';
import axios from 'axios';
import { type CMSConfigResponse, setCMSConfig } from '../lib/cms-config-types.js';

// Default values
const DEFAULTS = {
  contentDir: '.leadcms/content',
  commentsDir: '.leadcms/comments',
  mediaDir: 'public/media',
};

interface UserConfig {
  url: string;
  apiKey: string;
  defaultLanguage: string;
  contentDir: string;
  mediaDir: string;
  commentsDir: string;
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

/**
 * Promisified question function
 */
function question(query: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(query, resolve);
  });
}

/**
 * Fetch CMS configuration from API
 * This is a public endpoint that does not require authentication
 */
async function fetchCMSConfig(url: string): Promise<CMSConfigResponse | null> {
  try {
    const apiUrl = new URL('/api/config', url).toString();

    // /api/config is a public endpoint - never send Authorization header
    const response = await axios.get<CMSConfigResponse>(apiUrl, {
      timeout: 10000,
    });

    // Cache the config for use by other operations
    if (response.data) {
      setCMSConfig(response.data);
    }

    return response.data;
  } catch (error: any) {
    if (error.code === 'ECONNREFUSED') {
      console.error('❌ Could not connect to LeadCMS. Please check the URL.');
    } else {
      console.error(`❌ Failed to fetch CMS config: ${error.message}`);
    }
    return null;
  }
}

/**
 * Validate URL format
 */
function isValidUrl(url: string): boolean {
  try {
    new URL(url);
    return url.startsWith('http://') || url.startsWith('https://');
  } catch {
    return false;
  }
}

/**
 * Create or update .env file
 */
function updateEnvFile(config: UserConfig): void {
  const envPath = path.join(process.cwd(), '.env');
  const envLocalPath = path.join(process.cwd(), '.env.local');

  // Check which file to use
  const targetEnvFile = fs.existsSync(envLocalPath) ? envLocalPath : envPath;

  let envContent = '';

  // Read existing content if file exists
  if (fs.existsSync(targetEnvFile)) {
    envContent = fs.readFileSync(targetEnvFile, 'utf-8');
  }

  // Parse existing env vars
  const envVars = new Map<string, string>();
  envContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key) {
        envVars.set(key.trim(), valueParts.join('=').trim());
      }
    }
  });

  // Update with new values
  envVars.set('LEADCMS_URL', config.url);
  if (config.apiKey) {
    envVars.set('LEADCMS_API_KEY', config.apiKey);
  } else {
    // Remove API key if it exists but user wants anonymous mode
    envVars.delete('LEADCMS_API_KEY');
  }
  envVars.set('LEADCMS_DEFAULT_LANGUAGE', config.defaultLanguage);

  // Build new content
  const newLines: string[] = [];
  newLines.push('# LeadCMS Configuration');
  newLines.push('# Generated by leadcms init');
  if (!config.apiKey) {
    newLines.push('# Running in anonymous mode - only public content accessible');
    newLines.push('# Add LEADCMS_API_KEY for write operations and private content');
  }
  newLines.push('');

  envVars.forEach((value, key) => {
    newLines.push(`${key}=${value}`);
  });

  fs.writeFileSync(targetEnvFile, newLines.join('\n') + '\n', 'utf-8');
  console.log(`✅ Updated ${path.basename(targetEnvFile)}`);
}

/**
 * Create leadcms.config.json if needed
 */
function createConfigFile(config: UserConfig): void {
  const configPath = path.join(process.cwd(), 'leadcms.config.json');

  // Only create config if values differ from defaults
  const needsConfig =
    config.contentDir !== DEFAULTS.contentDir ||
    config.mediaDir !== DEFAULTS.mediaDir ||
    config.commentsDir !== DEFAULTS.commentsDir;

  if (!needsConfig) {
    console.log('ℹ️  Using default directories, no leadcms.config.json needed.');
    return;
  }

  const configData: any = {};

  if (config.contentDir !== DEFAULTS.contentDir) {
    configData.contentDir = config.contentDir;
  }

  if (config.mediaDir !== DEFAULTS.mediaDir) {
    configData.mediaDir = config.mediaDir;
  }

  if (config.commentsDir !== DEFAULTS.commentsDir) {
    configData.commentsDir = config.commentsDir;
  }

  fs.writeFileSync(
    configPath,
    JSON.stringify(configData, null, 2) + '\n',
    'utf-8'
  );

  console.log(`✅ Created leadcms.config.json`);
}

/**
 * Main initialization flow
 */
async function main(): Promise<void> {
  console.log('\n🚀 LeadCMS SDK Initialization\n');

  const config: UserConfig = {
    url: '',
    apiKey: '',
    defaultLanguage: 'en',
    contentDir: DEFAULTS.contentDir,
    mediaDir: DEFAULTS.mediaDir,
    commentsDir: DEFAULTS.commentsDir,
  };

  // Check if config already exists
  const configPath = path.join(process.cwd(), 'leadcms.config.json');
  const envPath = path.join(process.cwd(), '.env');
  const envLocalPath = path.join(process.cwd(), '.env.local');

  if (fs.existsSync(configPath) || fs.existsSync(envPath) || fs.existsSync(envLocalPath)) {
    const answer = await question('⚠️  Configuration files already exist. Overwrite? (y/N): ');
    if (answer.toLowerCase() !== 'y' && answer.toLowerCase() !== 'yes') {
      console.log('✅ Initialization cancelled.');
      rl.close();
      return;
    }
    console.log('');
  }

  // Step 1: Get LeadCMS URL
  while (!config.url) {
    const urlInput = await question('Enter your LeadCMS URL (e.g., https://your-instance.leadcms.io): ');
    const trimmedUrl = urlInput.trim().replace(/\/$/, ''); // Remove trailing slash

    if (!trimmedUrl) {
      console.log('❌ URL is required.\n');
      continue;
    }

    if (!isValidUrl(trimmedUrl)) {
      console.log('❌ Invalid URL format. Must start with http:// or https://\n');
      continue;
    }

    config.url = trimmedUrl;
  }

  // Step 2: Get API Key (optional)
  console.log('');
  const apiKeyInput = await question('Enter your LeadCMS API Key (or press Enter for anonymous mode): ');
  config.apiKey = apiKeyInput.trim();

  if (!config.apiKey) {
    console.log('ℹ️  Anonymous mode: Only public content will be accessible.');
    console.log('   Read operations will work, but write operations (push) will fail.');
  }

  // Step 3: Fetch CMS configuration (public endpoint, no authentication required)
  console.log('\n🔍 Connecting to LeadCMS...');
  let cmsConfig: CMSConfigResponse | null = null;
  cmsConfig = await fetchCMSConfig(config.url);

  // Track which entities are supported
  let supportsContent = false;
  let supportsMedia = false;
  let supportsComments = false;

  if (!cmsConfig) {
    console.log('\n⚠️  Could not fetch CMS configuration. Continuing with manual setup...\n');

    // Manual default language input
    const langInput = await question(`Default language code [${config.defaultLanguage}]: `);
    if (langInput.trim()) {
      config.defaultLanguage = langInput.trim();
    }

    // Default to all types when config is not available
    supportsContent = supportsMedia = supportsComments = false;
  } else {
    // Successfully fetched CMS config
    console.log('✅ Connected successfully!\n');

    // Set default language from CMS
    config.defaultLanguage = cmsConfig.defaultLanguage;

    console.log('📋 Available languages:');
    cmsConfig.languages.forEach((lang: { code: string; name: string }, idx: number) => {
      const marker = lang.code === cmsConfig!.defaultLanguage ? '(default)' : '';
      console.log(`   ${idx + 1}. ${lang.name} [${lang.code}] ${marker}`);
    });
    console.log(`\n✓ Using default language: ${config.defaultLanguage}\n`);

    // Check which entities are supported
    if (cmsConfig.entities && Array.isArray(cmsConfig.entities) && cmsConfig.entities.length > 0) {
      const entityNames = cmsConfig.entities.map((e: string) => e.toLowerCase());
      supportsContent = entityNames.includes('content');
      supportsMedia = entityNames.includes('media');
      supportsComments = entityNames.includes('comment') || entityNames.includes('comments');

      console.log('📦 Supported entity types:');
      if (supportsContent) console.log('   ✓ Content');
      if (supportsMedia) console.log('   ✓ Media');
      if (supportsComments) console.log('   ✓ Comments');

      if (!supportsContent && !supportsMedia && !supportsComments) {
        console.log('   ⚠️  No matching entity types found');
        console.log('\n💡 This LeadCMS instance does not support standard entity types.');
        console.log('   Configuration will be created without directory prompts.\n');
      } else {
        console.log('');
      }
    } else {
      // Empty or missing entities array - don't assume anything
      console.log('📦 Supported entity types:');
      console.log('   ⚠️  No entities information available');
      console.log('\n💡 Cannot determine supported entity types from the API.');
      console.log('   Configuration will be created without directory prompts.\n');
    }
  }

  // Step 4: Ask for directories only for supported entity types
  if (supportsContent) {
    const contentDirInput = await question(`Content directory [${DEFAULTS.contentDir}]: `);
    if (contentDirInput.trim()) {
      config.contentDir = contentDirInput.trim();
    }
  }

  if (supportsMedia) {
    const mediaDirInput = await question(`Media directory [${DEFAULTS.mediaDir}]: `);
    if (mediaDirInput.trim()) {
      config.mediaDir = mediaDirInput.trim();
    }
  }

  if (supportsComments) {
    const commentsDirInput = await question(`Comments directory [${DEFAULTS.commentsDir}]: `);
    if (commentsDirInput.trim()) {
      config.commentsDir = commentsDirInput.trim();
    }
  }

  console.log('\n📝 Creating configuration files...\n');

  // Create .env file
  updateEnvFile(config);

  // Create config file if needed
  createConfigFile(config);

  console.log('\n✨ Configuration complete!\n');
  console.log('Next steps:');
  console.log('  1. Run: npx leadcms pull');
  console.log('  2. Start using LeadCMS content in your project\n');

  rl.close();
}

// Run the script
main().catch((error) => {
  console.error('❌ Initialization failed:', error.message);
  rl.close();
  process.exit(1);
});
